routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/annonce/create', [App\Http\Controllers\AnnonceController::class, 'create'])->name('annonce.create');
Route::post('/annonce/create', [App\Http\Controllers\AnnonceController::class, 'store'])->name('annonce.store');
Route::get('/annonces', [App\Http\Controllers\AnnonceController::class, 'index'])->name('annonce.index');
Route::post('/annonces', [App\Http\Controllers\AnnonceController::class, ''])->name('annonces');
Route::get('/annonce/{id}', [App\Http\Controllers\AnnonceController::class, 'show'])->name('annonces.show');
Route::get('/annonce/{id}/inscription', [App\Http\Controllers\AnnonceController::class, 'inscription'])->name('annonce.inscription');
Route::get('/annonce/supprimer/{id}', 'App\Http\Controllers\AnnonceController@destroy')->name('annonce.destroy');

Route::get('/admin/users/{id}', 'App\Http\Controllers\Admin\UsersController@destroy')->name('users.destroy');

Route::post('/professeur', 'App\Http\Controllers\ProfesseurController@store')->name('professeur.store');

Route::get('/profile','App\Http\Controllers\Admin\UsersController@show')->name('user.show');

Route::get('/professeur/profile/{id}', 'App\Http\Controllers\ProfesseurController@show')->name('professeur.show');

Route::get('/professeur/edit/{id}', 'App\Http\Controllers\ProfesseurController@edit')->name('professeur.edit');

Route::get('/professeur/update/{id}', 'App\Http\Controllers\ProfesseurController@update')->name('professeur.update');

Route::get('/professeur/destroy/{id}', 'App\Http\Controllers\ProfesseurController@destroy')->name('professeur.destroy');

Route::get('/professeur/create', 'App\Http\Controllers\ProfesseurController@create')->name('professeur.create');

Route::post('/etudiant', 'App\Http\Controllers\EtudiantController@store')->name('etudiant.store');

Route::get('/etudiant/profile/{id}', 'App\Http\Controllers\EtudiantController@show')->name('etudiant.show');

Route::get('/etudiant/edit/{id}', 'App\Http\Controllers\EtudiantController@edit')->name('etudiant.edit');

Route::get('/etudiant/update/{id}', 'App\Http\Controllers\EtudiantController@update')->name('etudiant.update');

Route::get('/etudiant/destroy/{id}', 'App\Http\Controllers\EtudiantController@destroy')->name('etudiant.destroy');

Route::get('/etudiant/create', 'App\Http\Controllers\EtudiantController@create')->name('etudiant.create');

Route::resource('/admin/users', 'App\Http\Controllers\Admin\UsersController');

Route::namespace('App\Http\Controllers\Admin')->prefix('/admin')->name('admin.')->middleware('can:admin-users')->group(function() {
    Route::resource('users', 'UsersController');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function roles()
    {
        return $this->belongsToMany('App\Models\Role');
    }

    public function isAdmin()
    {
        return $this->roles()->where('name', 'admin')->first();
    }

    public function isEtudiant()
    {
        return $this->roles()->where('name', 'etudiant')->first();
    }

    public function isProfesseur()
    {
        return $this->roles()->where('name', 'professeur')->first();
    }

    public function hasAnyRole(array $roles)
    {
        return $this->roles()->whereIn('name', $roles)->first();
    }

    public function etudiant(){
        return $this->hasOne(Etudiant::class);
    }
    public function professeur(){
        return $this->hasOne(Professeur::class);
    }


}

app/Http/Controllers/Admin/UsersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Role;
use App\Models\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Gate;
use Illuminate\Http\Request;
use Monolog\Handler\RollbarHandler;

class UsersController extends Controller
{
    public function __construct(){
        $this->middleware(('auth'));
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();
        return view('admin.users.index')->with('users', $users);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     * @return \Illuminate\Http\Response
     */
    public function show()
    {
        $u = Auth::user();
        $user = User::find($u->id);
        if($user->isEtudiant()){
            $etudiant = $user->etudiant;
            $annonces = $etudiant->annonces;
            return view('user.show',['etudiant'=>$etudiant,'user'=>$user,'annonces'=>$annonces]);
        }
        elseif($user->isProfesseur()){
            $professeur = $user->professeur;
            $annonces = $professeur->annonces;
            return view('user.show',['professeur'=>$professeur,'user'=>$user,'annonces'=>$annonces]);
        }




    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        if(Gate::denies('admin-users')){
            return redirect()->route('admin.users.index');
        }

        $roles = Role::all();

        return view('admin.users.edit', [
            'user' => $user,
            'roles' => $roles
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $user->roles()->sync($request->roles);

        return redirect()->route('admin.users.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if(Gate::denies('admin-users')){
            return redirect()->route('admin.users.index');
        }
        $user = User::find($id);
        if($user->isProfesseur()){
            $prof = $user->professeur;
            $prof->delete();
            $user->roles()->detach();
            $user->delete();

            return redirect('/admin/users');
        }
        elseif($user->isEtudiant()){
            $etu = $user->etudiant;
            $etu->delete();
            $user->roles()->detach();
            $user->delete();

            return redirect('/admin/users');
        }
    }
}

resources/views/admin/users/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Modifier <strong>{{ $user->name }}</strong></div>
                <div class="card-body">
                  <form action="{{ route('admin.users.update', $user) }}" method="POST">
                    @csrf
                    @method('PATCH')
                    @foreach ($roles as $role)
                        <div class='form-group form-check'>
                            <input type="checkbox" class="form-check-input" name="roles[]" value="{{ $role->id }}" 
                            id=" {{ $role->id }}" @foreach ($user->roles as $userRole)
                                @if($userRole->id == $role->id) checked @endif
                            @endforeach>
                            <label for="{{ $role->id}}" class = "form-check-label">{{$role->name}}</label>
                        </div>
                    @endforeach
                    <button type="submit" class="btn btn-primary">Modifier les rôles</button>  
                  </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/users/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Liste des utilisateurs') }}</div>
                <div class="card-body">
                    <table class="table">
                        <thead>
                          <tr>
                            <th scope="col"> # </th>
                            <th scope="col">Nom</th>
                            <th scope="col">Email</th>
                            <th scope="col">Role</th>
                            <th scope="col">actions</th>
                          </tr>
                        </thead>
                        <tbody>
                            @foreach ($users as $user)
                                <tr>
                                    <td scope="row">{{ $user->id }}</td>
                                    <td>{{ $user->name }}</td>
                                    <td>{{ $user->email }}</td>
                                    <td>{{ implode(', ', $user->roles()->get()->pluck('name')->toArray()) }}</td>
                                    <td>
                                        <a href="{{ route('admin.users.edit', $user->id) }}">
                                            <button type="button" class="btn btn-primary">
                                                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-pencil" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                                    <path fill-rule="evenodd" d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5L13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175l-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"></path>
                                                </svg>
                                            </button>
                                        </a>
                                        <a href="{{ route('admin.users.destroy', $user->id) }}" >
                                            <button type="button" class="btn btn-danger">
                                                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-archive-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                                    <path fill-rule="evenodd" d="M12.643 15C13.979 15 15 13.845 15 12.5V5H1v7.5C1 13.845 2.021 15 3.357 15h9.286zM5.5 7a.5.5 0 0 0 0 1h5a.5.5 0 0 0 0-1h-5zM.8 1a.8.8 0 0 0-.8.8V3a.8.8 0 0 0 .8.8h14.4A.8.8 0 0 0 16 3V1.8a.8.8 0 0 0-.8-.8H.8z"></path>
                                                </svg>
                                            </button>
                                        </a>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                      </table>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/users/show.blade.php
@extends('layouts.app')
@section('content')
    @if($user->isEtudiant())
    <h1><strong>Mon profile</strong></h1>
    <div class="col-md-12">
        <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
            <div class="col p-4 d-flex flex-column position-static">
                <h5 class="mb-0"><strong>Etudiant</strong></h5>
                <hr>
                <p class="mb-auto text-muted"><strong>Nom: </strong>{{$user->name}}</p>
                <hr>
                <p class="mb-auto text-muted"><strong>Prenom: </strong>{{$etudiant->prenom}}</p>
                <hr>
                <p class="mb-auto text-muted"><strong>Date de Naissance: </strong>{{$etudiant->dateDeNaissance}}</p>
                <hr>
                <p class="mb-auto text-muted"><strong>Niveau: </strong>{{$etudiant->niveau}}</p>
                <hr>
                <p class="mb-auto text-muted"><strong>Adresse Mail: </strong>{{$user->email}}</p>
                <hr>
            </div>
        </div>
    </div>
    <div>
        <h1><strong>Mes cours</strong></h1>
        @foreach($annonces as $annonce)
            <div class="col-md-12">
                <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                    <div class="col p-4 d-flex flex-column position-static">
                        <strong class="d-inline-block mb-2 text-success">{{$annonce->matiere}}</strong>
                        <h5 class="mb-0">{{ $annonce->titre }}</h5>
                        <hr>
                        <p class="mb-auto text-muted">{{ $annonce->description }}</p>
                        <strong class="mb-auto font-weight-normal text-secondary">{{ $annonce->prix }}</strong>
                    </div>
                </div>
            </div>
        @endforeach
    </div>
    @elseif($user->isProfesseur())
        <h1><strong>Mon profile</strong></h1>
        <div class="col-md-12">
            <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                <div class="col p-4 d-flex flex-column position-static">
                    <h5 class="mb-0"><strong>Professeur</strong></h5>
                    <hr>
                    <p class="mb-auto text-muted"><strong>Nom: </strong>{{$professeur->nom}}</p>
                    <hr>
                    <p class="mb-auto text-muted"><strong>Prenom: </strong>{{$professeur->prenom}}</p>
                    <hr>
                    <p class="mb-auto text-muted"><strong>Adresse Mail: </strong>{{$user->email}}</p>
                    <hr>
                </div>
            </div>
        </div>
        <div>
            <h1><strong>Mes annonces</strong></h1>
            @foreach($annonces as $annonce)
                <div class="col-md-12">
                    <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                        <div class="col p-4 d-flex flex-column position-static">
                            <strong class="d-inline-block mb-2 text-success">{{$annonce->matiere}}</strong>
                            <h5 class="mb-0">{{ $annonce->titre }}</h5>
                            <hr>
                            <p class="mb-auto text-muted">{{ $annonce->description }}</p>
                            <strong class="mb-auto font-weight-normal text-secondary">{{ $annonce->prix }}</strong>
                        </div>
                    </div>
                </div>
            @endforeach
        </div>
    @endif
@endsection