routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/annonce/create', [App\Http\Controllers\AnnonceController::class, 'create'])->name('annonce.create');
Route::post('/annonce/create', [App\Http\Controllers\AnnonceController::class, 'store'])->name('annonce.store');
Route::get('/annonces', [App\Http\Controllers\AnnonceController::class, 'index'])->name('annonce.index');
Route::post('/annonces', [App\Http\Controllers\AnnonceController::class, ''])->name('annonces');
Route::get('/annonce/{id}', [App\Http\Controllers\AnnonceController::class, 'show'])->name('annonces.show');
Route::get('/annonce/{id}/inscription', [App\Http\Controllers\AnnonceController::class, 'inscription'])->name('annonce.inscription');
Route::get('/annonce/supprimer/{id}', 'App\Http\Controllers\AnnonceController@destroy')->name('annonce.destroy');

Route::get('/admin/users/{id}', 'App\Http\Controllers\Admin\UsersController@destroy')->name('users.destroy');

Route::post('/professeur', 'App\Http\Controllers\ProfesseurController@store')->name('professeur.store');

Route::get('/profile','App\Http\Controllers\Admin\UsersController@show')->name('user.show');

Route::get('/professeur/profile/{id}', 'App\Http\Controllers\ProfesseurController@show')->name('professeur.show');

Route::get('/professeur/edit/{id}', 'App\Http\Controllers\ProfesseurController@edit')->name('professeur.edit');

Route::get('/professeur/update/{id}', 'App\Http\Controllers\ProfesseurController@update')->name('professeur.update');

Route::get('/professeur/destroy/{id}', 'App\Http\Controllers\ProfesseurController@destroy')->name('professeur.destroy');

Route::get('/professeur/create', 'App\Http\Controllers\ProfesseurController@create')->name('professeur.create');

Route::post('/etudiant', 'App\Http\Controllers\EtudiantController@store')->name('etudiant.store');

Route::get('/etudiant/profile/{id}', 'App\Http\Controllers\EtudiantController@show')->name('etudiant.show');

Route::get('/etudiant/edit/{id}', 'App\Http\Controllers\EtudiantController@edit')->name('etudiant.edit');

Route::get('/etudiant/update/{id}', 'App\Http\Controllers\EtudiantController@update')->name('etudiant.update');

Route::get('/etudiant/destroy/{id}', 'App\Http\Controllers\EtudiantController@destroy')->name('etudiant.destroy');

Route::get('/etudiant/create', 'App\Http\Controllers\EtudiantController@create')->name('etudiant.create');

Route::resource('/admin/users', 'App\Http\Controllers\Admin\UsersController');

Route::namespace('App\Http\Controllers\Admin')->prefix('/admin')->name('admin.')->middleware('can:admin-users')->group(function() {
    Route::resource('users', 'UsersController');
});

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}" class="h-100">
<head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body class="d-flex flex-column h-100">
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Se connecter') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __("S'inscrire") }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name}} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                    onclick="event.preventDefault();
                                             document.getElementById('logout-form').submit();">{{ __('Se Déconnecter') }}</a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                    @can('admin-users')
                                    <a class="dropdown-item" href="{{ route('admin.users.index') }}">{{ __('Liste Des Utilisateurs') }}</a>
                                    @endcan
                                    @can('prof-users')
                                    <a class="dropdown-item" href="{{ route('annonce.create') }}">{{ __('Créer Une Annonce')}}</a>
                                    @endcan
                                    @cannot('admin-users')
                                    <a class="dropdown-item" href="{{ route('user.show') }}">{{ __('Mon Profile')}}</a>
                                    @endcannot
                                    <a class="dropdown-item" href="{{ route('annonce.index') }}">{{ __('Liste Des Annonces')}}</a>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-3">
            @yield('content')
        </main>

        <footer class="footer mt-auto py-3 bg-light">
            <div class="container-fluid row">
              <span class="col-md-5 text-muted">L'imagination est plus importante que le savoir</span>
              <svg width="2em" height="2em" viewBox="0 0 17 17" class="bi bi-bootstrap-fill col-md-1" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <title>Bootstrap</title>
                <path fill-rule="evenodd" d="M4.002 0a4 4 0 0 0-4 4v8a4 4 0 0 0 4 4h8a4 4 0 0 0 4-4V4a4 4 0 0 0-4-4h-8zm1.06 12h3.475c1.804 0 2.888-.908 2.888-2.396 0-1.102-.761-1.916-1.904-2.034v-.1c.832-.14 1.482-.93 1.482-1.816 0-1.3-.955-2.11-2.542-2.11H5.062V12zm1.313-4.875V4.658h1.78c.973 0 1.542.457 1.542 1.237 0 .802-.604 1.23-1.764 1.23H6.375zm0 3.762h1.898c1.184 0 1.81-.48 1.81-1.377 0-.885-.65-1.348-1.886-1.348H6.375v2.725z"/>
              </svg>
              <svg xmlns="http://www.w3.org/2000/svg" width="2em" height="2em" class="col-md-1" viewBox="0 0 84.1 57.6">
                <title>laravel</title>
                <path fill="#fb503b" d="M83.8 26.9c-.6-.6-8.3-10.3-9.6-11.9-1.4-1.6-2-1.3-2.9-1.2s-10.6 1.8-11.7 1.9c-1.1.2-1.8.6-1.1 1.6.6.9 7 9.9 8.4 12l-25.5 6.1L21.2 1.5c-.8-1.2-1-1.6-2.8-1.5C16.6.1 2.5 1.3 1.5 1.3c-1 .1-2.1.5-1.1 2.9S17.4 41 17.8 42c.4 1 1.6 2.6 4.3 2 2.8-.7 12.4-3.2 17.7-4.6 2.8 5 8.4 15.2 9.5 16.7 1.4 2 2.4 1.6 4.5 1 1.7-.5 26.2-9.3 27.3-9.8 1.1-.5 1.8-.8 1-1.9-.6-.8-7-9.5-10.4-14 2.3-.6 10.6-2.8 11.5-3.1 1-.3 1.2-.8.6-1.4zm-46.3 9.5c-.3.1-14.6 3.5-15.3 3.7-.8.2-.8.1-.8-.2-.2-.3-17-35.1-17.3-35.5-.2-.4-.2-.8 0-.8S17.6 2.4 18 2.4c.5 0 .4.1.6.4 0 0 18.7 32.3 19 32.8.4.5.2.7-.1.8zm40.2 7.5c.2.4.5.6-.3.8-.7.3-24.1 8.2-24.6 8.4-.5.2-.8.3-1.4-.6s-8.2-14-8.2-14L68.1 32c.6-.2.8-.3 1.2.3.4.7 8.2 11.3 8.4 11.6zm1.6-17.6c-.6.1-9.7 2.4-9.7 2.4l-7.5-10.2c-.2-.3-.4-.6.1-.7.5-.1 9-1.6 9.4-1.7.4-.1.7-.2 1.2.5.5.6 6.9 8.8 7.2 9.1.3.3-.1.5-.7.6z"/></svg>
              <span class="text-right text-muted col-md-5">Par Kevin, Yanis et Louis</span>
            </div>
          </footer>
    </div>
</body>
</html>